add fluentd-gcp repo
kubernetes-sigs/instrumentation-addons pull request #2
Opened 2021-04-15 02:28 UTC by coffeepac

adds fluentd-gcp from https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-gcp
fluentd-gcp will be remove in k/k in: <still buildling>
fixes: kubernetes/kubernetes#79432

2021-05-14 02:36 UTC, coffeepac commented
/verify-owners

2021-05-14 20:13 UTC, coffeepac commented
/verify-owners

2021-05-14 20:47 UTC, ehashman requested changes

2021-05-14 20:47 UTC, ehashman commented on OWNERS_ALIAS
> +aliases:
Remove this file

2021-05-14 20:47 UTC, ehashman commented
/verify-owners

should work now

2021-05-14 20:48 UTC, ehashman commented
/hold

to remove redundant OWNERS_ALIAS file

2021-05-17 16:23 UTC, coffeepac commented
@ehashman errant file removed, thank you for sorting that out!

2021-06-10 18:35 UTC, ehashman reviewed
/hold cancel
/lgtm
/approve

2021-06-10 18:37 UTC, merged